# -*- coding: utf-8 -*-
import json
import io
from PIL import Image, ImageTk
# Form implementation generated from reading ui file 'api.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import requests
from PyQt5.QtCore import Qt
from PyQt5.QtGui import QImage, QPixmap, QTextCharFormat
import tkinter as tk

class Ui_Api(object):
    def setupUi(self, Api):
        Api.setObjectName("Api")
        Api.resize(846, 746)
        self.gridLayout_13 = QtWidgets.QGridLayout(Api)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.CommonBox = QtWidgets.QGridLayout()
        self.CommonBox.setContentsMargins(16, 45, 16, 16)
        self.CommonBox.setSpacing(16)
        self.CommonBox.setObjectName("CommonBox")
        self.PicBox = QtWidgets.QVBoxLayout()
        self.PicBox.setObjectName("PicBox")
        self.PicTitle = SubtitleLabel(Api)
        self.PicTitle.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(15)
        font.setBold(True)
        self.PicTitle.setFont(font)
        self.PicTitle.setObjectName("PicTitle")
        self.PicBox.addWidget(self.PicTitle)
        self.PicCard = SimpleCardWidget(Api)
        self.PicCard.setMinimumSize(QtCore.QSize(380, 0))
        self.PicCard.setMaximumSize(QtCore.QSize(380, 16777215))
        self.PicCard.setObjectName("PicCard")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.PicCard)
        self.gridLayout_4.setContentsMargins(16, 16, 16, 16)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")


        self.ComboBox = ComboBox(self.PicCard)
        self.ComboBox.setMinimumSize(QtCore.QSize(300, 0))
        self.ComboBox.setMaximumSize(QtCore.QSize(16777215, 30))
        self.ComboBox.setObjectName("ComboBox")
        self.verticalLayout.addWidget(self.ComboBox)
        self.PrimaryPushButton_2 = PrimaryPushButton(self.PicCard)
        self.PrimaryPushButton_2.setObjectName("PrimaryPushButton_2")
        self.verticalLayout.addWidget(self.PrimaryPushButton_2)
        self.PrimaryPushButton = PrimaryPushButton(self.PicCard)
        self.PrimaryPushButton.setObjectName("PrimaryPushButton")
        self.verticalLayout.addWidget(self.PrimaryPushButton)
        self.gridLayout_4.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.PicBox.addWidget(self.PicCard)
        self.CommonBox.addLayout(self.PicBox, 1, 0, 1, 1)
        self.VideoClipBox = QtWidgets.QVBoxLayout()
        self.VideoClipBox.setObjectName("VideoClipBox")
        self.VideoClipLabel = SubtitleLabel(Api)
        self.VideoClipLabel.setMinimumSize(QtCore.QSize(0, 25))
        self.VideoClipLabel.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(15)
        font.setBold(True)
        self.VideoClipLabel.setFont(font)
        self.VideoClipLabel.setObjectName("VideoClipLabel")
        self.VideoClipBox.addWidget(self.VideoClipLabel)
        self.VideoClipCard = SimpleCardWidget(Api)
        self.VideoClipCard.setMinimumSize(QtCore.QSize(0, 170))
        self.VideoClipCard.setMaximumSize(QtCore.QSize(16777215, 170))
        self.VideoClipCard.setObjectName("VideoClipCard")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.VideoClipCard)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.StrongBodyLabel = StrongBodyLabel(self.VideoClipCard)
        self.StrongBodyLabel.setObjectName("StrongBodyLabel")
        self.verticalLayout_4.addWidget(self.StrongBodyLabel)
        #______________________________________________________________________________________________________






        self.textBrowser_2 = QtWidgets.QTextBrowser(self.VideoClipCard)
        self.textBrowser_2.setMaximumSize(QtCore.QSize(370, 16777215))
        self.textBrowser_2.setAutoFillBackground(False)
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.verticalLayout_4.addWidget(self.textBrowser_2)














        self.gridLayout_10.addLayout(self.verticalLayout_4, 0, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.BodyLabel = BodyLabel(self.VideoClipCard)
        self.BodyLabel.setMaximumSize(QtCore.QSize(340, 16777215))
        self.BodyLabel.setObjectName("BodyLabel")
        self.verticalLayout_3.addWidget(self.BodyLabel)
        self.ComboBox_2 = ComboBox(self.VideoClipCard)
        self.ComboBox_2.setMinimumSize(QtCore.QSize(340, 0))
        self.ComboBox_2.setMaximumSize(QtCore.QSize(340, 16777215))
        self.ComboBox_2.setObjectName("ComboBox_2")
        self.verticalLayout_3.addWidget(self.ComboBox_2)
        self.BodyLabel_2 = BodyLabel(self.VideoClipCard)
        self.BodyLabel_2.setMaximumSize(QtCore.QSize(340, 16777215))
        self.BodyLabel_2.setObjectName("BodyLabel_2")
        self.verticalLayout_3.addWidget(self.BodyLabel_2)
        self.SearchLineEdit_2 = SearchLineEdit(self.VideoClipCard)
        self.SearchLineEdit_2.setMaximumSize(QtCore.QSize(340, 33))
        self.SearchLineEdit_2.setObjectName("SearchLineEdit_2")
        self.verticalLayout_3.addWidget(self.SearchLineEdit_2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.gridLayout_10.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.VideoClipBox.addWidget(self.VideoClipCard)
        self.CommonBox.addLayout(self.VideoClipBox, 2, 0, 1, 2)
        self.AudioParmsBox = QtWidgets.QGridLayout()
        self.AudioParmsBox.setObjectName("AudioParmsBox")
        self.AudioParmsTitle = SubtitleLabel(Api)
        self.AudioParmsTitle.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(15)
        font.setBold(True)
        self.AudioParmsTitle.setFont(font)
        self.AudioParmsTitle.setObjectName("AudioParmsTitle")
        self.AudioParmsBox.addWidget(self.AudioParmsTitle, 0, 0, 1, 1)
        self.AudioParmsCard = SimpleCardWidget(Api)
        self.AudioParmsCard.setMinimumSize(QtCore.QSize(380, 0))
        self.AudioParmsCard.setMaximumSize(QtCore.QSize(300, 16777215))
        self.AudioParmsCard.setObjectName("AudioParmsCard")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.AudioParmsCard)
        self.horizontalLayout.setContentsMargins(16, 16, 16, 16)
        self.horizontalLayout.setSpacing(16)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.BodyLabel_3 = BodyLabel(self.AudioParmsCard)
        self.BodyLabel_3.setObjectName("BodyLabel_3")
        self.verticalLayout_2.addWidget(self.BodyLabel_3)
        self.SearchLineEdit = SearchLineEdit(self.AudioParmsCard)
        self.SearchLineEdit.setObjectName("SearchLineEdit")
        self.verticalLayout_2.addWidget(self.SearchLineEdit)



        self.textBrowser = QtWidgets.QTextBrowser(self.AudioParmsCard)
        self.textBrowser.setMinimumSize(QtCore.QSize(340, 0))
        self.textBrowser.setMaximumSize(QtCore.QSize(200, 16777215))
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout_2.addWidget(self.textBrowser)




        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.AudioParmsBox.addWidget(self.AudioParmsCard, 1, 0, 1, 1)
        self.CommonBox.addLayout(self.AudioParmsBox, 1, 1, 1, 1)
        self.CommonTitile = LargeTitleLabel(Api)
        self.CommonTitile.setMaximumSize(QtCore.QSize(16777215, 45))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(30)
        font.setBold(True)
        font.setKerning(True)
        self.CommonTitile.setFont(font)
        self.CommonTitile.setObjectName("CommonTitile")
        self.CommonBox.addWidget(self.CommonTitile, 0, 0, 1, 2)
        self.gridLayout_13.addLayout(self.CommonBox, 0, 1, 1, 1)

        self.retranslateUi(Api)
        self.ComboBox.addItem("黑丝")
        self.ComboBox.addItem("白丝")
        self.ComboBox.addItem("随机美女")
        self.PrimaryPushButton_2.clicked.connect(self.getgirl)
        self.PrimaryPushButton.clicked.connect(self.dlpic)
        self.SearchLineEdit.searchButton.clicked.connect(self.animeyou)
        global status
        status="none"
        self.ComboBox_2.addItem("傲娇姐姐-叶婧AI")
        self.ComboBox_2.addItem("软萌妹妹-沫沫AI")
        self.ComboBox_2.addItem("病态女友-黑羽AI")
        self.SearchLineEdit_2.searchButton.clicked.connect(self.aigf)
        format = QTextCharFormat()
        format.setFontFamily("楷体")
        format.setFontPointSize(13)
        format.setForeground(Qt.white)
        self.textBrowser_2.setStyleSheet("background:transparent;border-width:0;border-style:outset")
        self.textBrowser_2.setCurrentCharFormat(format)
        QtCore.QMetaObject.connectSlotsByName(Api)
    def getgirl(self):
        print(self.ComboBox.currentText())
        global reference
        reference=""
        if self.ComboBox.currentText()=="黑丝":
            reference="heisi"
        elif self.ComboBox.currentText()=="白丝":
            reference="baisi"
        else:
            reference="meinvpic"
        url = "https://v2.api-m.com/api/"+reference
        status="yes"


        response = requests.get(url)
        url2=json.loads(response.text)["data"]
        print(url2)
        global piccode
        piccode=requests.get(url2).content
        root=tk.Tk()
        data_stream = io.BytesIO(piccode)
        # 转换为图片格式
        pil_image = Image.open(data_stream)
        # 获取图片的宽度和高度
        w, h = pil_image.size
        # 获取图片的文件名
        fname = url.split('/')[-1]
        sf = "{} ({}x{})".format(fname, w, h)
        # 设置窗口title
        root.title(sf)
        # 将pil格式的图片转换为tk格式的image
        tk_image = ImageTk.PhotoImage(pil_image)
        # 创建个label组件, root作为父节点
        label = tk.Label(root, image=tk_image, bg='black')
        # 设置一些padding
        label.pack(padx=5, pady=5)
        root.mainloop()
    def aigf(self):
        if self.SearchLineEdit_2.text()!="":
            print("yes")

            if self.ComboBox_2.currentText()=="傲娇姐姐-叶婧AI":
                print("yj")
                dic1=json.loads(requests.get("https://api.lolimi.cn/API/AI/jj.php?msg="+self.SearchLineEdit_2.text()).text)["data"]
                self.textBrowser_2.append("你:"+dic1["content"])
                self.textBrowser_2.append("叶婧:" + dic1["output"])
                print(dic1["output"])
            elif self.ComboBox_2.currentText()=="软萌妹妹-沫沫AI":
                print("mm")
                dic1 = json.loads(requests.get("https://api.lolimi.cn/API/AI/mm.php?msg="+self.SearchLineEdit_2.text()).text)["data"]
                self.textBrowser_2.append("你:"+dic1["content"])
                self.textBrowser_2.append("沫沫:" + dic1["output"])
                print(dic1["output"])
            else:
                print("yy")
                dic1 = json.loads(requests.get("https://api.lolimi.cn/API/AI/bj.php?msg="+self.SearchLineEdit_2.text()).text)["data"]
                self.textBrowser_2.append("你:"+dic1["content"])
                self.textBrowser_2.append("黑雨:" + dic1["output"])
                print(dic1["output"])
        else:
            print("no")
            w = MessageBox(
                '失败',
                '还没有输入你的名字哦',
                self
            )
            w.yesButton.setText('确定')
            w.cancelButton.setText('取消')

            if w.exec():
                pass

    def animeyou(self):
        if self.SearchLineEdit.text()!="":
            url="https://api.lolimi.cn/API/Ser/?name="+self.SearchLineEdit.text()+"&type=text"
            print(requests.get(url).text)
            self.textBrowser.setText(requests.get(url).text)
        else:
            print("no")
            w = MessageBox(
                '失败',
                '还没有输入你的名字哦',
                self
            )
            w.yesButton.setText('确定')
            w.cancelButton.setText('取消')

            if w.exec():
                pass


    def dlpic(self):
        print("lihai")
        if status=="yes":
            print("yes")
            with open("image.jpg","wb") as f:
                f.write(piccode)
        else:
            print("no")
            w = MessageBox(
                '失败',
                '当前还未获取图片',
                self
            )
            w.yesButton.setText('确定')
            w.cancelButton.setText('取消')

            if w.exec():
                pass
    def retranslateUi(self, Api):
        _translate = QtCore.QCoreApplication.translate
        Api.setWindowTitle(_translate("Common", "Form"))
        self.PicTitle.setText(_translate("Common", "丝袜API"))
        format=QTextCharFormat()
        format.setFontFamily("楷体")
        format.setFontPointSize(13)
        format.setForeground(Qt.white)
        self.textBrowser.setStyleSheet("background:transparent;border-width:0;border-style:outset")
        self.textBrowser.setCurrentCharFormat(format)
        self.textBrowser_2.setCurrentCharFormat(format)
        self.PrimaryPushButton_2.setText(_translate("Common", "获取"))
        self.PrimaryPushButton.setText(_translate("Common", "下载"))
        self.VideoClipLabel.setText(_translate("Common", "AI女友对话api"))
        self.StrongBodyLabel.setText(_translate("Common", "对话记录"))
        self.BodyLabel.setText(_translate("Common", "请选择模型"))
        self.BodyLabel_2.setText(_translate("Common", "请输入你想说的话"))
        self.AudioParmsTitle.setText(_translate("Common", "文字类API"))
        self.BodyLabel_3.setText(_translate("Common", "二次元的你"))
        self.CommonTitile.setText(_translate("Common", "奇奇怪怪的API"))
from qfluentwidgets import BodyLabel, ComboBox, ImageLabel, LargeTitleLabel, PrimaryPushButton, SearchLineEdit, \
    SimpleCardWidget, StrongBodyLabel, SubtitleLabel, MessageBox
