# -*- coding: utf-8 -*-
import datetime
import time
# Form implementation generated from reading ui file 'd:\Jason Shen\Documents\MihiroToolbox\UI\QtDesigner\common.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

from qfluentwidgets import InfoBarIcon, InfoBar, PushButton, setTheme, Theme, FluentIcon, InfoBarPosition, \
    InfoBarManager, BodyLabel, ProgressRing
from bs4 import BeautifulSoup
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
from PyQt5.QtCore import *
import requests
from urllib.request import urlopen,Request
import psutil
from PyQt5.QtWidgets import *
from PyQt5.QtCore import QObject,QRect
import sys

# headers = {'User-Agent':'Mozilla/5.0 (Windows NT 6.1; WOW64; rv:23.0) Gecko/20100101 Firefox/23.0'}
# req = Request(url="https://ip.900cha.com/#google_vignette", headers=headers)
# html=urlopen(req).read()
# bs = BeautifulSoup(html,"html.parser")
# nameList = bs.find_all("li",{"class":"list-item mt-2"})
# city=nameList[1].getText()[13:].split(" ")[3]+"   "+nameList[1].getText()[13:].split(" ")[4]+"   "+nameList[1].getText()[13:].split(" ")[5]
# rep = requests.get('http://www.tianqiapi.com/api?version=v6&appid=68279872&appsecret=szWI7YeK&city='+nameList[1].getText()[13:].split(" ")[5].strip())
# rep.encoding = 'utf-8'
# print(nameList[1].getText()[13:].split(" ")[5])
# print(rep.json())

class Ui_dll(object):

    def __init__(self):
        self.timer = QTimer()
        self.timer.timeout.connect(self.time_display)
        self.timer_switch_flag = False
        self.timer2 = QTimer()
        self.timer2.timeout.connect(self.time_display2)
        self.timer_switch_flag2 = False
    def setupUi(self, Common):
        Common.setObjectName("Common")
        Common.resize(1250, 809)
        self.gridLayout_13 = QtWidgets.QGridLayout(Common)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.CommonBox = QtWidgets.QGridLayout()
        self.CommonBox.setContentsMargins(16, 45, 16, 16)
        self.CommonBox.setSpacing(16)
        self.CommonBox.setObjectName("CommonBox")
        self.CommonTitile = LargeTitleLabel(Common)
        self.CommonTitile.setMaximumSize(QtCore.QSize(16777215, 45))

        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.CommonTitile.setFont(font)
        self.CommonTitile.setObjectName("CommonTitile")
        self.CommonBox.addWidget(self.CommonTitile, 0, 0, 1, 2)
        self.PicBox = QtWidgets.QVBoxLayout()
        self.PicBox.setObjectName("PicBox")
        self.PicTitle = SubtitleLabel(Common)
        self.PicTitle.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.PicTitle.setFont(font)
        self.PicTitle.setObjectName("PicTitle")
        self.PicBox.addWidget(self.PicTitle)
        self.PicCard = SimpleCardWidget(Common)
        self.PicCard.setObjectName("PicCard")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.PicCard)
        self.gridLayout_4.setContentsMargins(16, 16, 16, 16)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.AudioInputBox = QtWidgets.QGridLayout()
        self.AudioInputBox.setObjectName("AudioInputBox")
        self.AudioInputLabel = BodyLabel(self.PicCard)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.AudioInputLabel.setFont(font)
        self.AudioInputLabel.setObjectName("AudioInputLabel")
        self.AudioInputBox.addWidget(self.AudioInputLabel, 0, 0, 1, 1)

        self.AudioInputLabel2 = BodyLabel(self.PicCard)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.AudioInputLabel2.setFont(font)
        self.AudioInputLabel2.setObjectName("AudioInputLabel2")
        self.AudioInputBox.addWidget(self.AudioInputLabel2, 1, 0, 1, 1)

        self.gridLayout_4.addLayout(self.AudioInputBox, 1, 0, 1, 1)
        self.VideoOutputBox_2 = QtWidgets.QGridLayout()
        self.VideoOutputBox_2.setObjectName("VideoOutputBox_2")
        self.VideoOutputLabel_2 = BodyLabel(self.PicCard)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.VideoOutputLabel_2.setFont(font)
        self.VideoOutputLabel_2.setObjectName("VideoOutputLabel_2")
        self.VideoOutputBox_2.addWidget(self.VideoOutputLabel_2, 0, 0, 1, 1)
        self.VideoOutputLabel = BodyLabel(self.PicCard)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.VideoOutputLabel.setFont(font)
        self.VideoOutputLabel.setObjectName("VideoOutputLabel")
        self.VideoOutputBox_2.addWidget(self.VideoOutputLabel, 1, 0, 1, 1)

        self.gridLayout_4.addLayout(self.VideoOutputBox_2, 2, 0, 1, 1)
        self.PicInputBox = QtWidgets.QGridLayout()
        self.PicInputBox.setObjectName("PicInputBox")
        self.InputLabel = BodyLabel(self.PicCard)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.InputLabel.setFont(font)
        self.InputLabel.setObjectName("InputLabel")
        self.PicInputBox.addWidget(self.InputLabel, 0, 0, 1, 1)

        self.InputLabel2=BodyLabel(self.PicCard)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.InputLabel2.setFont(font)
        self.InputLabel2.setObjectName("InputLabel2")
        self.PicInputBox.addWidget(self.InputLabel2, 1, 0, 1, 1)

        self.gridLayout_4.addLayout(self.PicInputBox, 0, 0, 1, 1)
        self.PicBox.addWidget(self.PicCard)
        self.CommonBox.addLayout(self.PicBox, 1, 0, 1, 1)
        self.AudioParmsBox = QtWidgets.QGridLayout()
        self.AudioParmsBox.setObjectName("AudioParmsBox")
        self.AudioParmsTitle = SubtitleLabel(Common)
        self.AudioParmsTitle.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.AudioParmsTitle.setFont(font)
        self.AudioParmsTitle.setObjectName("AudioParmsTitle")
        self.AudioParmsBox.addWidget(self.AudioParmsTitle, 0, 0, 1, 1)
        self.AudioParmsCard = SimpleCardWidget(Common)
        self.AudioParmsCard.setMinimumSize(QtCore.QSize(350, 0))
        self.AudioParmsCard.setObjectName("AudioParmsCard")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.AudioParmsCard)
        self.horizontalLayout.setContentsMargins(16, 16, 16, 16)
        self.horizontalLayout.setSpacing(16)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ParmsBox = QtWidgets.QVBoxLayout()
        self.ParmsBox.setObjectName("ParmsBox")
        self.BitrateBox = QtWidgets.QVBoxLayout()
        self.BitrateBox.setObjectName("BitrateBox")
        self.BitrateLabel = BodyLabel(self.AudioParmsCard)
        self.BitrateLabel.setObjectName("BitrateLabel")
        self.BitrateBox.addWidget(self.BitrateLabel)

        self.BitrateLabel2 = ProgressRing(self.AudioParmsCard)

        self.BitrateLabel2.setMinimumSize(QtCore.QSize(50, 50))
        self.BitrateLabel2.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.BitrateLabel2.setFont(font)

        self.BitrateLabel2.setProperty("value", 10)

        self.BitrateLabel2.setTextVisible(True)



        self.BitrateLabel2.setVal(50.0)
        self.BitrateLabel2.setStrokeWidth(10)
        self.BitrateLabel2.setObjectName("FpsLabel2")
        self.BitrateBox.addWidget(self.BitrateLabel2)
        self.ParmsBox.addLayout(self.BitrateBox)
        self.FpsBox = QtWidgets.QVBoxLayout()
        self.FpsBox.setObjectName("FpsBox")
        self.FpsLabel = BodyLabel(self.AudioParmsCard)
        self.FpsLabel.setObjectName("FpsLabel")
        self.FpsBox.addWidget(self.FpsLabel)

        self.FpsLabel2 = ProgressRing(self.AudioParmsCard)


        self.FpsLabel2.setMinimumSize(QtCore.QSize(50, 50))
        self.FpsLabel2.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.FpsLabel2.setFont(font)

        self.FpsLabel2.setProperty("value", 10)

        self.FpsLabel2.setTextVisible(True)

        self.FpsLabel2.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.FpsLabel2.setUseAni(False)
        self.FpsLabel2.setVal(50.0)
        self.FpsLabel2.setStrokeWidth(10)
        self.FpsLabel2.setObjectName("FpsLabel2")

        self.FpsBox.addWidget(self.FpsLabel2)
        self.ParmsBox.addLayout(self.FpsBox)
        self.CrfBox = QtWidgets.QVBoxLayout()
        self.CrfBox.setObjectName("CrfBox")
        self.CrfLabel = BodyLabel(self.AudioParmsCard)
        self.CrfLabel.setObjectName("CrfLabel")
        self.CrfBox.addWidget(self.CrfLabel)
        self.CrfLabel2 = ProgressRing(self.AudioParmsCard)
        self.CrfLabel2.setMinimumSize(QtCore.QSize(50, 50))
        self.CrfLabel2.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.CrfLabel2.setFont(font)
        self.CrfLabel2.setProperty("value", 10)
        self.CrfLabel2.setTextVisible(True)
        self.CrfLabel2.setVal(50.0)
        self.CrfLabel2.setStrokeWidth(10)
        self.CrfLabel2.setObjectName("FpsLabel2")
        self.CrfBox.addWidget(self.CrfLabel2)
        self.ParmsBox.addLayout(self.CrfBox)
        self.horizontalLayout.addLayout(self.ParmsBox)
        self.TimeBox = QtWidgets.QVBoxLayout()
        self.TimeBox.setContentsMargins(-1, 0, -1, 0)
        self.TimeBox.setSpacing(25)
        self.TimeBox.setObjectName("TimeBox")
        self.InnerTimeBox = QtWidgets.QGridLayout()
        self.InnerTimeBox.setObjectName("InnerTimeBox")



        self.TimeBox.addLayout(self.InnerTimeBox)
        self.ProcessStartButton = PrimaryPushButton(self.AudioParmsCard)
        self.ProcessStartButton.setObjectName("ProcessStartButton")
        self.ProcessStartButton.clicked.connect(lambda : self.display_switch())

        self.TimeBox.addWidget(self.ProcessStartButton)

        self.horizontalLayout.addLayout(self.TimeBox)
        self.AudioParmsBox.addWidget(self.AudioParmsCard, 1, 0, 1, 1)
        #fenge

        #fenge
        self.CommonBox.addLayout(self.AudioParmsBox, 1, 1, 1, 1)
        self.VideoClipBox = QtWidgets.QVBoxLayout()
        self.VideoClipBox.setObjectName("VideoClipBox")
        self.VideoClipLabel = SubtitleLabel(Common)
        self.VideoClipLabel.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)



        self.CommonBox.addLayout(self.VideoClipBox, 2, 0, 1, 2)
        self.TransposeBox = QtWidgets.QVBoxLayout()
        self.TransposeBox.setObjectName("TransposeBox")
        self.TransposeTitle = SubtitleLabel(Common)
        self.TransposeTitle.setMaximumSize(QtCore.QSize(16777215, 25))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.TransposeTitle.setFont(font)
        self.TransposeTitle.setObjectName("TransposeTitle")
        self.TransposeBox.addWidget(self.TransposeTitle)
        self.TransposeCard = SimpleCardWidget(Common)
        self.TransposeCard.setMinimumSize(QtCore.QSize(0, 80))
        self.TransposeCard.setObjectName("TransposeCard")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.TransposeCard)
        self.gridLayout_11.setContentsMargins(16, 16, 16, 16)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.InnerTransposeBox = QtWidgets.QHBoxLayout()
        self.InnerTransposeBox.setSpacing(24)
        self.InnerTransposeBox.setObjectName("InnerTransposeBox")
        self.OptionBox = QtWidgets.QHBoxLayout()
        self.OptionBox.setSpacing(6)
        self.OptionBox.setObjectName("OptionBox")
        self.OptionLabel = BodyLabel(self.TransposeCard)
        self.OptionLabel.setMaximumSize(QtCore.QSize(120, 16777215))
        self.OptionLabel.setObjectName("OptionLabel")
        self.OptionBox.addWidget(self.OptionLabel)

        self.InnerTransposeBox.addLayout(self.OptionBox)
        self.TransposeButton = PrimaryPushButton(self.TransposeCard)
        self.TransposeButton.setMaximumSize(QtCore.QSize(120, 16777215))
        self.TransposeButton.setObjectName("TransposeButton")
        self.InnerTransposeBox.addWidget(self.TransposeButton)
        self.gridLayout_11.addLayout(self.InnerTransposeBox, 0, 0, 1, 1)

        self.TransposeBox.addWidget(self.TransposeCard)
        self.CommonBox.addLayout(self.TransposeBox, 3, 0, 1, 2)
        self.gridLayout_13.addLayout(self.CommonBox, 0, 0, 1, 1)
        self.TransposeButton.clicked.connect(lambda : self.display_switch2())
        self.retranslateUi(Common)
        QtCore.QMetaObject.connectSlotsByName(Common)

    def retranslateUi(self, Common):
        _translate = QtCore.QCoreApplication.translate
        Common.setWindowTitle(_translate("Common", "Form"))
        self.CommonTitile.setText(_translate("Common", "常用"))
        self.PicTitle.setText(_translate("Common", "天气预报"))
        self.AudioInputLabel.setText(_translate("Common", "目前天气"))
        # self.AudioInputLabel2.setText(_translate("Common","天气："+rep.json()["wea"]+"       温度："+rep.json()["tem"]+'°C'))
        # self.VideoOutputLabel_2.setText(_translate("Common", "风的信息"))
        # self.VideoOutputLabel.setText(_translate("Common","风向："+rep.json()["win"]+"       风速："+rep.json()["win_speed"]))
        # self.InputLabel.setText(_translate("Common", "当前城市"))
        # self.InputLabel2.setText(_translate("Common",city))
        self.AudioParmsTitle.setText(_translate("Common", "系统占用"))
        self.BitrateLabel.setText(_translate("Common", "CPU占用"))
        self.BitrateLabel2.setFormat(_translate("Common", "请点击开始计算"))
        self.FpsLabel.setText(_translate("Common", "C盘占用"))
        self.FpsLabel2.setFormat(_translate("Common", "请点击开始计算"))
        self.CrfLabel.setText(_translate("Common", "RAM占用"))
        self.CrfLabel2.setFormat(_translate("Common", "请点击开始计算"))

        self.ProcessStartButton.setText(_translate("Common", "开始计算"))

        self.TransposeTitle.setText(_translate("Common", "当前时间"))
        self.OptionLabel.setText(_translate("Common", "请点击显示时间"))
        self.TransposeButton.setText(_translate("Common", "显示时间"))
    def display_switch(self):
        if not self.timer_switch_flag:
            self.timer.start(1000)
            self.timer_switch_flag = True
            self.ProcessStartButton.setText("停止显示")


        else:
            self.timer.stop()
            self.timer_switch_flag = False
            self.ProcessStartButton.setText("开始计算")

    def display_switch2(self):
        if not self.timer_switch_flag2:
            self.timer2.start(1000)
            self.timer_switch_flag2 = True
            self.TransposeButton.setText("停止显示")


        else:
            self.timer2.stop()
            self.timer_switch_flag2 = False
            self.TransposeButton.setText("显示时间")
    def clear_label_2(self):
        self.BitrateLabel2.setText('')
    def time_display(self):

        d = psutil.disk_partitions()[0]
        # 生成一个时间显示为"HH:MM:SS"的字符串
        cpu_str = str(psutil.cpu_percent())
        self.BitrateLabel2.setFormat(cpu_str+"%")
        self.BitrateLabel2.setProperty("value",psutil.cpu_percent())
        ram_str=str(psutil.virtual_memory().percent)
        # self.CrfLabel2.setText("当前ram占用:"+ram_str+"%")
        self.CrfLabel2.setFormat(ram_str + "%")
        self.CrfLabel2.setProperty("value", psutil.virtual_memory().percent)
        disk_info=psutil.disk_usage(d.device)
        self.FpsLabel2.setFormat(str(disk_info.percent)+"%")
        self.FpsLabel2.setProperty("value", disk_info.percent)
    def time_display2(self):
        # 生成一个时间显示为"HH:MM:SS"的字符串
        time_str = datetime.datetime.now().strftime('%T')
        self.OptionLabel.setText("现在是："+time_str)
        # 分秒为00:00，代表整点


from qfluentwidgets import BodyLabel, ComboBox, DoubleSpinBox, IndeterminateProgressBar, LargeTitleLabel, LineEdit, PrimaryPushButton, PushButton, SimpleCardWidget, SpinBox, SubtitleLabel
